### ISSUE TITLE
Error: called `Result::unwrap()` on an `Err` value: "Error running snarkjs: "

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/zk_bench#8]
### Aim

Gather benchmark numbers using the repo.

### Expected Behavior

Runs `cargo run`, gets numbers.

### Bug

Gets the error:
```
called `Result::unwrap()` on an `Err` value: "Error running snarkjs: "
```

Full trace:

```
% RUST_BACKTRACE=full cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/zk_bench`
Benchmarking...
thread 'main' panicked at src/main.rs:6:18:
called `Result::unwrap()` on an `Err` value: "Error running snarkjs: "
stack backtrace:
   0:        0x1041df8e4 - std::backtrace_rs::backtrace::libunwind::trace::h6de1cbf3f672a4f8
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:        0x1041df8e4 - std::backtrace_rs::backtrace::trace_unsynchronized::hd0de2d5ef13b6f4d
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1041df8e4 - std::sys_common::backtrace::_print_fmt::h2a33510d9b3bb866
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:68:5
   3:        0x1041df8e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h01b2beffade888b2
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x1041f944c - core::fmt::rt::Argument::fmt::h5ddc0f22b2928899
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/fmt/rt.rs:142:9
   5:        0x1041f944c - core::fmt::write::hbadb443a71b75f23
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/fmt/mod.rs:1153:17
   6:        0x1041dd328 - std::io::Write::write_fmt::hc09d7755e3ead5f0
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/io/mod.rs:1843:15
   7:        0x1041df73c - std::sys_common::backtrace::_print::h3cd1786cbb1caf0f
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x1041df73c - std::sys_common::backtrace::print::h28349e5c25acbac7
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x1041e0c50 - std::panicking::default_hook::{{closure}}::hd24b6196784d991e
  10:        0x1041e0934 - std::panicking::default_hook::hfcec80a2720c8c73
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:292:9
  11:        0x1041e1544 - std::panicking::rust_panic_with_hook::h84760468187ddc85
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:779:13
  12:        0x1041e0f30 - std::panicking::begin_panic_handler::{{closure}}::he666a5eb600a7203
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:657:13
  13:        0x1041dfd68 - std::sys_common::backtrace::__rust_end_short_backtrace::h592f44d2bf9f843f
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:171:18
  14:        0x1041e0ca8 - rust_begin_unwind
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
  15:        0x104200bb4 - core::panicking::panic_fmt::h98bbf7bdf4994454
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
  16:        0x104200f3c - core::result::unwrap_failed::h8e3b933261dd7fec
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
  17:        0x1041820dc - core::result::Result<T,E>::unwrap::h6b1f8d7a731f3eb9
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1077:23
  18:        0x1041820dc - zk_bench::main::hb2f8bb7469fac131
                               at /Users/s/Dev/noir-lang/zk_bench/src/main.rs:6:5
  19:        0x104182f68 - core::ops::function::FnOnce::call_once::hfefbb7dc05d44687
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
  20:        0x104181f74 - std::sys_common::backtrace::__rust_begin_short_backtrace::h23dba2bd5f591453
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:155:18
  21:        0x104183d98 - std::rt::lang_start::{{closure}}::h4fac3e401948d181
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:166:18
  22:        0x1041d9f18 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::heaba8a29e0324069
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:284:13
  23:        0x1041d9f18 - std::panicking::try::do_call::h6e5fac4f4884d97b
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
  24:        0x1041d9f18 - std::panicking::try::h2b98e2f3cf76cd78
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
  25:        0x1041d9f18 - std::panic::catch_unwind::hba9c97319335c08b
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
  26:        0x1041d9f18 - std::rt::lang_start_internal::{{closure}}::h18efdcfb68f002e8
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:48
  27:        0x1041d9f18 - std::panicking::try::do_call::ha793e16770aada4d
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
  28:        0x1041d9f18 - std::panicking::try::h8aa812e3e1310d12
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
  29:        0x1041d9f18 - std::panic::catch_unwind::h38c4879f2623185e
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
  30:        0x1041d9f18 - std::rt::lang_start_internal::h39923ab4c3913741
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:20
  31:        0x104183d64 - std::rt::lang_start::ha25aaffef297dcec
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:165:17
  32:        0x104182138 - _main
```

### To Reproduce

(Rust and NPM installed and updated)

Circom & Snarkjs installation:
1. `git clone https://github.com/iden3/circom.git`
2. `cd circom`
3. `cargo build --release`
4. `cargo install --path circom`
5. `npm install -g snarkjs`

Run benchmarks:
6. `git clone https://github.com/noir-lang/zk_bench.git`
7. `cargo run` / `RUST_BACKTRACE=full cargo run`
8. Gets the error above

### Environment

- macOS
- Rust versions:
  ```
  stable-aarch64-apple-darwin (default)
  rustc 1.78.0 (9b00956e5 2024-04-29)
  ```

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
You need to install the yarn dependencies as snarkjs is an npm package.

**Comment by Savio-Sou** [comment]
Ah thanks, got it working now. Will PR the commands to run into the README.
